//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImpuestoRentaApp.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImpuestoRentaTipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImpuestoRentaTipo()
        {
            this.ImpuestoRenta = new HashSet<ImpuestoRenta>();
        }
    
        public int impuestorentatipo_id { get; set; }
        public string descripcion_impuesto_renta_tipo { get; set; }
        public bool esta_activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImpuestoRenta> ImpuestoRenta { get; set; }
    }
}
